name: Accessibility Test Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'

jobs:
  accessibility-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Debug Info
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          date

      - name: Hello
        run: echo "Helooo...!"
